Numpy documentation is very usefull in the following exercices. A specific set of exercices is given, aimed at handling datawrangling procedures.

In [5]:
#importing required packages
import numpy as np


In [8]:
#basic list to numpy array conversion
x = [1, 1, 2, 3, 5, 8, 13, 21, 34]
print('class is:', x.__class__)
print(x)

a = np.array(x)
print('class is:', a.__class__)
print(a)
print('has datatype:', a.dtype)

class is: <class 'list'>
[11, 55, 20, 78]
class is: <class 'numpy.ndarray'>
[11 55 20 78]
has datatype: int32


In [9]:
#pay attention to dtype
x = [1, 1, 2, 3, 5, 8, 13, 21.0, 34]
print('class is:', x.__class__)
print(x)

a = np.array(x)
print('class is:', a.__class__)
print(a)
print('has datatype:', a.dtype)

class is: <class 'list'>
[1, 1, 2, 3, 5, 8, 13, 21.0, 34]
class is: <class 'numpy.ndarray'>
[ 1.  1.  2.  3.  5.  8. 13. 21. 34.]
has datatype: float64


In [10]:
#setting static dimensions
x = [1, 1, 2, 3, 5, 8, 13, 21, 34]
print('class is:', x.__class__)
print(x)

a = np.array(x, ndmin=2)
print('class is:', a.__class__)
print(a)
print('has datatype:', a.dtype)

class is: <class 'list'>
[1, 1, 2, 3, 5, 8, 13, 21, 34]
class is: <class 'numpy.ndarray'>
[[ 1  1  2  3  5  8 13 21 34]]
has datatype: int32


In [11]:
#try with nested list, notice format numpy-array
x = [[1, 3, 2, 1],
     [3, 5, 4, 3],
     [1, 3, 2, 1],
     [2, 4, 3, 2]]

print('class is:', x.__class__)
print(x)

a = np.array(x, ndmin=2)
print('class is:', a.__class__)
print(a)
print('has datatype:', a.dtype)

class is: <class 'list'>
[[1, 3, 2, 1], [3, 5, 4, 3], [1, 3, 2, 1], [2, 4, 3, 2]]
class is: <class 'numpy.ndarray'>
[[1 3 2 1]
 [3 5 4 3]
 [1 3 2 1]
 [2 4 3 2]]
has datatype: int32


Now for some simple warm-up on np.arange() function.


In [12]:
x = np.arange(11)
print('class is:', x.__class__)
print('has datatype:', a.dtype)
print(x)



class is: <class 'numpy.ndarray'>
has datatype: int32
[ 0  1  2  3  4  5  6  7  8  9 10]


In [13]:
x = np.arange(5,15)
print('class is:', x.__class__)
print('has datatype:', a.dtype)
print(x)


class is: <class 'numpy.ndarray'>
has datatype: int32
[ 5  6  7  8  9 10 11 12 13 14]


In [14]:
x = np.arange(5, 15, 3)
print('class is:', x.__class__)
print('has datatype:', a.dtype)
print(x)

class is: <class 'numpy.ndarray'>
has datatype: int32
[ 5  8 11 14]


In [17]:
x = np.arange(5, 15, 3, dtype='float')
print('class is:', x.__class__)
print('has datatype:', x.dtype)
print(x)

class is: <class 'numpy.ndarray'>
has datatype: float64
[ 5.  8. 11. 14.]


In [21]:
#dtype can be used to cast input or as a check
x = np.arange(5,15, 0.5)
print('class is:', x.__class__)
print('has datatype:', x.dtype)
print(x)

#downcasting
x = np.arange(5, 15, 0.5, dtype='int')
print('class is:', x.__class__)
print('has datatype:', x.dtype)
print(x)

#gives TypeError
x = np.arange(1, 11, 1, dtype='string')
    



class is: <class 'numpy.ndarray'>
has datatype: float64
[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5
 12.  12.5 13.  13.5 14.  14.5]
class is: <class 'numpy.ndarray'>
has datatype: int32
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


TypeError: data type "string" not understood

Some examples on np.reshape()

In [33]:
#reshaping into 2-d
x = np.array([1,1,2,3,5,8,13,21,34,55])
print('two ways to reshape')
print(x.reshape(2,5))
print(np.reshape(x,(2,5)), '\n')

x = np.array([1,1,2,3,5,8,13,21,34,55])
print(x.reshape(5,2))



two ways to reshape
[[ 1  1  2  3  5]
 [ 8 13 21 34 55]]
[[ 1  1  2  3  5]
 [ 8 13 21 34 55]] 

[[ 1  1]
 [ 2  3]
 [ 5  8]
 [13 21]
 [34 55]]


In [36]:
# reshaping can be done with -1
# this dimension contains as much elements as needed.
print(x.reshape(2,-1), '\n')
print(x.reshape(5,-1))

# x contains 10 elements. Cannot be reshaped into arrays of size 3
print(x.reshape(3,-1))

[[ 1  1  2  3  5]
 [ 8 13 21 34 55]] 

[[ 1  1]
 [ 2  3]
 [ 5  8]
 [13 21]
 [34 55]]


ValueError: cannot reshape array of size 10 into shape (3,newaxis)

np.fill(), np.zeros, np.ones() are handy functions for initializing numpy arrays.

In [45]:
#provide the dimensions of the numpy nd-array as tuples
print(np.zeros(3), '\n')
print(np.zeros((3,3)), '\n')
print(np.zeros((3,3,3), '\n'))

# same for np.ones
print(np.ones(4), '\n')
print(np.ones((1, 3)), '\n')
print(np.ones((3, 1)), '\n')

[0. 0. 0.] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[1. 1. 1. 1.] 

[[1. 1. 1.]] 

[[1.]
 [1.]
 [1.]] 



In [52]:
#fill can be used on existing arrays
x = np.array([2,3,6,5.0])
print(x, '\n')
#fill function has no return value
x.fill(0.)
print(x, '\n')
x.fill(np.pi)
print(x, '\n')

[2. 3. 6. 5.] 

[0. 0. 0. 0.] 

[3.14159265 3.14159265 3.14159265 3.14159265] 



In [1]:
# The .shape attribute is useful for determining dimensions of numpy array
# It returns a tuple containing the size of dimensions.
x = np.array([1,2,3])
y = np.array([[1,2,3]])
z = np.array([[1,2],[2,3],[3,4]])

display(x.shape)
display(y.shape)
display(z.shape)

NameError: name 'np' is not defined