A set of Exercices made for Numpy package

In [3]:
#import all the appropiate packages
import numpy as np

In [7]:
# Make a list, dict and tuple manually of size 3. convert these to numpy arrays 
# show the results using display(..) 


array([1, 2, 3])

array([1, 2, 3])

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [14]:
# create a 3x3 numpy array with values going from 2 to 10. 
# Do this in two different ways (there are more)


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

ValueError: can only specify one unknown dimension

In [29]:
# Take the 3x3 array created in the previous exercise
# convert it to 1x9 and a 9x1. Check the dimensions to be sure



array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

(1, 9)

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

(9, 1)

In [23]:
# make a numpy array of size 10 filled with zeros
# update one of the values to 7.0. update another value to 5.0. Update all even  values to 3.0


[3.0, 3.0, 7.0, 3.0, 5.0, 3.0, 3.0, 3.0, 3.0, 3.0]

In [33]:
# write a function that takes a numpy array as input
# the output of the function is a numpy array with the same dimensions but filled with 1's
# test it with an example and display




array([[1., 1., 1.],
       [1., 1., 1.]])