A set of Exercices made for Numpy package

In [2]:
#import all the appropiate packages
import numpy as np

In [4]:
# Make a list, dict and tuple manually of size 3. convert these to numpy arrays 
# show the results using display(..) 
list = [1,2,3]
dict = {"a":1,"b":2,"c":3}
tuple = (1,2,3)
npList = np.array(list)
npDict = np.array(dict)
npTuple = np.array(tuple)
display(npList)
display(npDict)
display(npTuple)

array([1, 2, 3])

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

array([1, 2, 3])

In [12]:
# create a 3x3 numpy array with values going from 2 to 10. 
# Do this in two different ways (there are more)
nump1 = np.array([[2,3,4],[5,6,7],[8,9,10]])
nump2 = np.arange(2,11).reshape(3,3)
display(nump2)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
# Take the 3x3 array created in the previous exercise
# convert it to 1x9 and a 9x1. Check the dimensions to be sure

nump3 = nump1.reshape(1,9)
nump4 = nump1.reshape(9,1)
display(nump3)
display(nump4)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [19]:
# make a numpy array of size 10 filled with zeros
# update one of the values to 7.0. update another value to 5.0. Update all even  values to 3.0
np1 = np.zeros(10,dtype=np.int8)
np1[0] = 7.0
np1[3] = 5.0
np1[np1 % 2 == 0] = 3.0
display(np1)

array([7, 3, 3, 5, 3, 3, 3, 3, 3, 3], dtype=int8)

In [33]:
# write a function that takes a numpy array as input
# the output of the function is a numpy array with the same dimensions but filled with 1's
# test it with an example and display




array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
def oneFiller(array):
    dimensions = np.shape(array)
    newArray = np.ones(dimensions)
    return newArray


testArray = np.array([[2, 2, 2],[2, 2, 2]])
newArray = oneFiller(testArray)
display(newArray)

array([[1., 1., 1.],
       [1., 1., 1.]])